deployment:
  name: api
  image: ayasagimbek/api-app
  tag: "2.0.0"
  port: 3001
  replicas: 2

service:
  name: api-service
  type: LoadBalancer
  port: 80
  targetPort: 3001

config:
  name: api-config
  data:
    DB: hello
    DBUSER: kaizen
    DBHOST: mysql-service 
    DBPORT: "3306"
    PORT: "3001"

secret:
  name: api-secret
  data:
    DBPASS: kaizen123