apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.name }}-secret
type: Opaque
stringData:
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}

