apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}-loadbalancer
  labels:
    app: {{ .Values.mysql.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.mysql.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mysql.port }}

apiVersion: v1
kind: Service
metadata:
  name: mysql-service    
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
