deployment:
  name: web
  image: ayasagimbek/web-app
  tag: "1.0.0"
  pullPolicy: Always
  port: 3000
  replicas: 2

service:
  name: web-service
  type: LoadBalancer
  port: 80
  targetPort: 3000

config:
  name: web-config

env:
  API_HOST: "http://api-service"
  PORT: 3000